# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run Linter Verification"
  lane :lint do
    gradle(task: "detekt")
  end

  desc "Run Test and Linter"
  lane :test_and_lint do
    gradle(task: "detekt")
    gradle(task: "test")
  end

  desc "Generate APK"
  lane :generate_apk do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
    sh("touch", "../apk_path.txt")
    ENV["APK_PATH"]=lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    output = ENV["APK_PATH"]
    sh "echo " + output + " >" + "../apk_path.txt"
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
