name: validate-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run linter"
        run: fastlane lint
      - name: "Run unit tests"
        run: fastlane test
      - name: "Run linter and unit tests"
        run: fastlane test_and_lint