name: validate-app
on:
  push:
    branches:
      - 'master'
jobs:
  lint-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Run linter"
        run: fastlane lint
      - name: "Run unit tests"
        run: fastlane test
      - name: "Run linter and unit tests"
        run: fastlane test_and_lint
  generate-apk:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Building the app"
        run: fastlane generate_apk
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: apk_path.txt
      - run: rm apk_path.txt
