name: validate-app
on:
  push:
    branches:
      - 'master'
jobs:
  test-lint-compile:
    name: "Executing Tests > Linting > Building"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Run unit tests"
        run: fastlane test
      - name: "Run linter"
        run: fastlane lint
      - name: "Building the app"
        run: fastlane generate_apk
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./apk_path.txt
      - run: rm ./apk_path.txt
