name: validate-app
on:
  push:
    branches:
      - 'master'
jobs:
  lint-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Run linter"
        run: bundle exec fastlane lint
      - name: "Run unit tests"
        run: bundle exec fastlane test
      - name: "Run linter and unit tests"
        run: bundle exec fastlane test_and_lint