name: validate-app
on:
  push:
    branches:
      - 'master'
jobs:
  linter:
    name: "Executing Linter"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Run linter"
        run: fastlane lint
  tests:
    name: "Executing Unit Tests"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: "Run unit tests"
        run: fastlane test
  generate-apk:
    name: "Generating APK Artifact"
    needs:
      - linter
      - tests
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/checkout@v2
      - name: "Building the app"
        run: fastlane generate_apk
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: apk_path.txt
      - run: rm apk_path.txt
